# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=300)),
                ('freq', models.IntegerField(default=1)),
                ('expStatus', models.IntegerField(default=200)),
                ('expString', models.TextField(max_length=1000)),
            ],
        ),
    ]
