# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlchecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=300)),
                ('timeChecked', models.DateTimeField()),
                ('statusCode', models.IntegerField(default=200)),
                ('state', models.TextField(max_length=20)),
            ],
        ),
    ]
