# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlchecker', '0002_urlchecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlchecks',
            name='timeChecked',
            field=models.TextField(max_length=20),
        ),
    ]
